In [1]:
import numpy as np
import matplotlib as plt 
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
X= dataset['data']
y = dataset['target']

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33)
X_train #it has 4 dimensions

array([[5.5, 2.4, 3.7, 1. ],
       [4.3, 3. , 1.1, 0.1],
       [4.9, 3.6, 1.4, 0.1],
       [7.7, 3. , 6.1, 2.3],
       [5.4, 3.9, 1.3, 0.4],
       [6.1, 2.8, 4. , 1.3],
       [7.2, 3.2, 6. , 1.8],
       [5.6, 3. , 4.5, 1.5],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.3, 1.7, 0.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.6, 2.7, 4.2, 1.3],
       [4.6, 3.2, 1.4, 0.2],
       [6.6, 3. , 4.4, 1.4],
       [4.6, 3.4, 1.4, 0.3],
       [6. , 3. , 4.8, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.2, 4.1, 1.5, 0.1],
       [4.8, 3.4, 1.9, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3.3, 5.7, 2.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.3, 2.9, 5.6, 1.8],
       [5.4, 3.4, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [5.8, 2.7, 3.9, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.8, 2

In [5]:
pca = PCA(n_components=3)

In [7]:
X_train = pca.fit_transform(X_train) #it will have only three dimensions
X_train

array([[-2.18020568e-01, -7.23487782e-01, -3.28603519e-01],
       [-3.25436111e+00, -5.37901650e-01,  1.21218856e-02],
       [-2.82605672e+00,  2.42424767e-01,  5.43849579e-02],
       [ 3.05819233e+00,  6.10867760e-01, -2.88315800e-01],
       [-2.64525066e+00,  7.72290808e-01,  1.25237232e-01],
       [ 3.33186599e-01, -1.21858080e-01, -2.30093194e-01],
       [ 2.59330919e+00,  5.01432069e-01, -1.90954776e-01],
       [ 6.27872698e-01, -4.07101307e-01,  3.10656803e-01],
       [-2.87883114e+00, -9.73921653e-01, -3.85156418e-01],
       [-2.65108606e+00,  1.34047125e-01, -5.52805977e-02],
       [-2.67257093e+00,  2.78243195e-01,  1.22149287e-03],
       [-2.32864905e+00,  6.04230664e-02,  1.68451602e-02],
       [ 1.44463652e+00,  4.48183301e-01, -3.24286409e-01],
       [ 3.26598567e-01, -5.54722375e-01, -1.54551857e-03],
       [-2.86824797e+00, -2.56648505e-01,  4.10652554e-02],
       [ 8.79126958e-01,  2.73327391e-01, -3.05693595e-01],
       [-2.85002585e+00, -1.21312105e-01

In [8]:
X_test = pca.transform(X_test)

In [9]:
pca.components_

array([[ 0.37196893, -0.08529549,  0.85433442,  0.35281227],
       [ 0.65293412,  0.73088239, -0.16654497, -0.10840079],
       [-0.55216772,  0.59315731,  0.05889773,  0.58292905]])

In [11]:
pca.explained_variance_ratio_ #if you combine these three then you will get 93% of variance is getting captured from the original data set

array([0.92492751, 0.05404382, 0.01468253])